/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_linglong_videocode_DataTransfer */

#ifndef _Included_com_linglong_videocode_DataTransfer
#define _Included_com_linglong_videocode_DataTransfer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_linglong_videocode_DataTransfer
 * Method:    nv21ToYuv420
 * Signature: ([B[BII)V
 */
JNIEXPORT void JNICALL Java_com_linglong_videocode_DataTransfer_nv21ToYuv420
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
